postgresql: &POSTGRES
  adapter: postgresql
  username: postgres
  password:
  database: beta_feature_test
  min_messages: ERROR

mysql: &MYSQL
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: beta_feature_test
  charset: utf8

test:
  <<: *<%= ENV['DB'] || 'POSTGRES' %>
